set(CI_PIPELINE_IID $ENV{CI_PIPELINE_IID})
if("${CI_PIPELINE_IID}" STREQUAL "")
    set(CI_PIPELINE_IID "0")
endif()

if(NOT ANDROID AND NOT IOS)
    set(DESKTOP_MODE ON)
endif()

if(NOT ANDROID AND NOT IOS)
    set(USE_GENERIC_SHARE_UTILS ON)
endif()
